apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: snapshot
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    cleanup.policy: compact
    segment.ms: 100
    min.cleanable.dirty.ratio: 0.01
    delete.retention.ms: 100
